### ISSUE TITLE
URL page can't be found.

### ISSUE THREAD

**Issue by liu00569** [liu00569/mtm6201-week1#1]
@abhaysharma
When I search liu00569/mtm6201-week1 the page can't be found.

**Comment by abhaysharma** [comment]
@liu00569 this is the URL of your GitHub Pages site https://liu00569.github.io/mtm6201-week1/ 

You can find it on the right side of your repository where it says "github-pages active". Or under Settings > Pages.

**Comment by liu00569** [comment]
But the liu00569.github.io is created last semester. When I check the repository, I can see the homework of this week is in the mtm6201-week1 repository. It's wired. Is it what things are supposes to be? @abhaysharma

**Comment by abhaysharma** [comment]
@liu00569 the liu00569.github.io is your GitHub Pages URL, it will be the first part of any repository that you add to GitHub pages.
Last semester you created a repository with the name liu00569.github.io which automatically links with the URL liu00569.github.io and hence you did not need to add anything at the end.
